### ISSUE TITLE
Tidak bisa play audio

### ISSUE THREAD

**Issue by unregister** [ngekoding/quran-id#4]
Assalamu'alaikum. Sebelumnya salam kenal mas.Terima kasih sudah membuatkan aplikasi ini. Semoga dengan adanya aplikasi ini, banyak orang yg mampir untuk sekedar membaca. Dan semoga Allah membalas semua amal baik ada, menjadi amal jariyah masnya kelak. 

Sebelumya saya sudah deploy aplikasi ini di http://alquranindonesia.web.id. Namun ketika saya play audionya, ternyata tidak mau keluar. Ada eror javascript. Sebelumnya saya sangat pemula dalam bahasa pemrograman vue, nodejs dan javascript bahkan bisa dikatakan baru belajar. Mohon bimbinganya mas. Terima kasih

Wassalamu'alaikum

**Comment by ngekoding** [comment]
Wa'alaikumussalam Warahmatullah Wabarakatuh

Terima kasih atas laporannya, akan coba saya cek dulu untuk lebih jelasnya. 

Terlebih sumber data yang digunakan adalah langsung merujuk ke sumber data quran.com seperti yang telah dijelaskan pada https://github.com/ngekoding/quran-id#install, barangkali ada masalah di sumber datanya.

**Comment by ngekoding** [comment]
Barusan saya cek audio masih bisa berjalan dengan lancar (Al-Fatihah by Mishary Rasyid).

Agar memudahkan untuk pengecekan lebih lanjut, barangkali bisa diberikan informasi pesan error yang dimaksud, termasuk informasi surah, ayat dan nama qarinya.

Terima kasih
